language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Beijing' # 更改时区

install:
  - npm install

script:
  # 为了能在git-pages预览 单独发布带有二级域名的包
  - npm run build
  # 默认(大部分)
  # - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "reborn233"
  - git config user.email "499289113@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://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@github.com/Reborn233/ts-game.git" master:gh-pages

branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/Reborn233/ts-game.git
